import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HomeComponent } from '@src/app/home/home.component';
import { RtdbComponent } from '@src/app/rtdb/rtdb.component';
import { RtdbDetailComponent } from '@src/app/rtdb/rtdb-detail/rtdb-detail.component';

export const routes: Routes = [
  {
    path: '',
    redirectTo: '/home',
    pathMatch: 'full',
  },
  {
    path: 'home',
    component: HomeComponent,
  },
  {
    path: 'rtdb',
    component: RtdbComponent,
  },
  {
    path: 'rtdb-detail/:id',
    component: RtdbDetailComponent,
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
