import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HomeComponent } from '@src/app/home/home.component';

// Import Angular Fire librairies needed
import { AngularFireDatabaseModule } from '@angular/fire/database';
import { AngularFireModule } from '@angular/fire';
import { environment } from '@src/environments/environment';



// Uncomment and add to NgModule imports if you need to use two-way binding
import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { RtdbComponent } from '@src/app/rtdb/rtdb.component';


// const config = {
//   apiKey: "AIzaSyCUG9jb6OUJJu0V4eQx05bcMK0oKOl1pe4",
//   authDomain: "ns-demo-4dd52.firebaseapp.com",
//   databaseURL: "https://ns-demo-4dd52.firebaseio.com",
//   projectId: "ns-demo-4dd52",
//   storageBucket: "ns-demo-4dd52.appspot.com",
//   messagingSenderId: "206323461764",
//   appId: "1:206323461764:web:c48c60e8277ebdb7825cd1",
//   measurementId: "G-DY2ZP7314E"

// }


@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    HomeComponent,
    RtdbComponent,
  ],
  imports: [
    // Angular Fire components import
    AngularFireDatabaseModule,
    AngularFireModule.initializeApp(environment.firebase),

    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
